### ISSUE TITLE
additional core logs

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#1022]
- [ ] body of metadata disk writes and reads
- [ ] body of requests and responses (for document contents, just the length)
- [ ] calls to public functions in lib.rs (including parameter values)
- [ ] beginning, end, and each intermediate call in sync

**Comment by tvanderstad** [comment]
secrets should be omitted across the board and/or this should be for dev builds only

**Comment by Parth** [comment]
Server should log every request and when it was made
