### ISSUE TITLE
windows/core: windows produces invalid drawings; core doesn't validate

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#1075]
steps:
1. create a drawing on windows
2. sync to macos
3. open the drawing

expected:
- drawing opens

actual:
- invalid alpha value

note: alpha is checked to be in the range [0, 1] by `export_drawing` but not by `save_drawing`. windows exports a value in the range [0, 255].

**Comment by Parth** [comment]
Are you sure windows is using `save_drawing`?
