### ISSUE TITLE
macos: markdown render update for code blocks

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#1077]
steps:
1. create a markdown document with content
~~~
```
```
~~~
2. add a newline as the first character

expected:
- first line not styled

actual:
- first line styled as code block

**Comment by Parth** [comment]
```
print("Code start line: \(node.cmarkNode.pointee.start_line), endline: \(node.cmarkNode.pointee.end_line), start_column: \(node.cmarkNode.pointee.start_column), end_column: \(node.cmarkNode.pointee.end_column)")
```

**Comment by Parth** [comment]
As you add newlines:
```
Document
    ↳ Code Block - fenceInfo: nil, content: nil
```

structure doesn't change

and therefore we do not restyle. I would have expected the underlying parser to return empty paragraphs for those regions.

Can't think of a workaround that won't significantly hinder performance, but maybe when I do the cross platform markdown toolkit my parser wouldn't behave this way.

**Comment by Parth** [comment]
+ swift does a lot of expensive conversions between different encodings
+ cmark gives utf 8 rows and cols
+ new swift uses utf 8
+ old swift libs that we have to use use utf 16

C mark already has us taking the ffi overhead, doing all the business logic in rust once and reusing it on all platforms could be great.

there's extra logic like auto insertion of bullets and whatnot that would be nice to write once, test once and use everywhere.

**Comment by Parth** [comment]
Actually it's not reasonable for a parser to show those as empty paragraphs, because they won't render that way.

I was able to come up with a workaround last night, I'll give that a go.
