### ISSUE TITLE
usage caps enforcement

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1297]
+ change-doc-content or upsert should not allow you to increase your usage beyond your cap
+ should gracefully inform the user as they're running out of space
+ should assign a constant (small) space cost per metadata

**Comment by SmailBarkouch** [comment]
We should also determine the data cap of a user using the expiration dates present on each payment profile.

**Comment by Parth** [comment]
*should assign a constant (small) space cost per metadata* 

disregards their deleted status
