### ISSUE TITLE
shares not populated

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1405]
(during finalization of files)

**Comment by tvanderstad** [comment]
work required to resolve this:
* add a public key -> username map and a username -> public key map as hmdb tables in core
* when you initiate a share, there is code to fetch the public key for that user; this code should be modified to add that usrename/key pair to both maps and to first check if the username -> public key map contains the username before looking it up
* server needs a GetUsername endpoint which does the reverse lookup that GetPublicKey does. server will not need a new hmdb table for this; it can use the accounts table to look up the account and the username is stored in the account
* at the end of a sync, core should go through all the pending shares, and if there's a sharer public key that isn't in the local maps yet, it should look up the username using the new server endpoint and store the result in both maps
* when finalizing files, look up the public keys of shares in the file user access keys and put the usernames in the share field

**Comment by tvanderstad** [comment]
on a related note, the 'last modified by' field is hardcoded as the current user during finalization of files, and should check the public key of the file signature and look it up in the maps added as part of this effort for the username of the last user to modify the file
