### ISSUE TITLE
Make sync progress more useful

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1435]

**Comment by Parth** [comment]
make this return `WorkCalculated`: https://github.com/lockbook/lockbook/blob/master/libs/core/src/lib.rs#L367

https://github.com/lockbook/lockbook/blob/master/libs/core/src/service/sync_service.rs#L95-L97

**Comment by steverusso** [comment]
Addressed by https://github.com/lockbook/lockbook/pull/1630
