### ISSUE TITLE
local usage history in core

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1449]

**Comment by Parth** [comment]
similar to #1296, define, in core, add 2 tables that keep track of the files the user reads / writes the most often, migrate over the old data into a new schema.

I'm thinking 2 tables with id -> usize (representing a count of read or write).

@SmailBarkouch how does android currently do recent files? it does it inside android based on metadata right? 

@ad-tra you should expose lib.rs endpoints and then work with smail to get android to show this information properly.

**Comment by ad-tra** [comment]
Instead of adding two tables that keep track of writes and reads per file, why not just add two attributes to the `FileMetadata` struct and store the info there?

also, what do you think about modeling read and write history as a time series instead of a counter? Collecting timestamps of the operations might allow us to perform smart personalization. I don't know if this is possible, given our commitment to data privacy, but an ideal state would have a small prediction engine that recommends files a user might want to read/edit based on past usage. 

Example: I have a doc `journal. md` that I append to each day before going to sleep at 11:00. It would be ideal for core to recommend `jounral.md` at night while suggesting different files in the morning.

**Comment by Parth** [comment]
Here's a whole bunch of surrounding context in addition to the answer to your q: 

> Instead of adding two tables that keep track of writes and reads per file, why not just add two attributes to the FileMetadata struct and store the info there?

`FileMetadata` is used everywhere and is perhaps one of the hardest structs to modify. It would take small not-really-breaking change and turn it unto a platform wide paradigm shift. It's possible that this data, or other data may make it's way into the struct at some point, but we want to be really sure about the things that do. Things that make it into `FileMetadata` impact all clients, all integrations, any servers without consideration for their use case. For something like `name` this is fine. For something like "metrics associated with reads and writes" there's a few more considerations:

The first is does this need to be synced? Does this data need to be backed up, replicated across devices, etc. Deciding yes may be tempting but is a literal cost to us, and in a lot of contexts it's nicer for devices to store info local-only. I'm interested in my work laptop, my phone, and my tablet having different histories and recommendations.

Having data be synced to the server also makes features online-only, we want to let people do mostly everything offline. So if this data needs to make it to the server then we need to decide at what point that happens, and what to do if the server's offline, what to do if someone changed the data after we read it, but before we wrote it. Generally an app would just make these interactions block for network access, but we want to be more thoughtful about this.

> >also, what do you think about modeling read and write history as a time series instead of a counter? Collecting timestamps of the operations might allow us to perform smart personalization. I don't know if this is possible, given our commitment to data privacy, but an ideal state would have a small prediction engine that recommends files a user might want to read/edit based on past usage.

We don't want to provide worse user experiences because of security / privacy reasons. It's a constraint, we want to design around that constraint, and here's how we think about this: 

The data that's synced we want to know as little about it as possible, so for instance we do need to know the ordering of events but we don't need to know the access history, we don't need to know the search index. So when that info is sent to the server we'd want to give consideration to what it's encrypted format is.

But if we're not syncing this information, we can be more flexible, we can experiment more and learn what model would be suitable for committing to. 

And surely this would be more expressive, but it would be more complicated, take longer to implement. And there's an ongoing thought to keeping track of more history already: https://github.com/lockbook/lockbook/issues/190. But perhaps we would still do it separately as to not have to read all the documents.


So yeah, if you're just storing ids and numbers ([timestamps] or a single count), and keeping them locally, or you could do that. But I'm suggesting the simplest initial version of this feature that'll get us 80% of the value, and we can continue to explore. Keep this are in the back of your head and we can revisit.
