### ISSUE TITLE
bulleted lists with checkboxes mixed in don't show up as checkboxes 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1606]
![image](https://user-images.githubusercontent.com/821972/221046237-8fff1aa9-a5fe-4613-9132-ffb671f47d83.png)

**Comment by tvanderstad** [comment]
minimally reproducing doc:
```
- [ ] 

-
```

**Comment by tvanderstad** [comment]
the AST produced in this case places `[ ]` in a paragraph rather than the item; this is due to a [pulldown-cmark bug](https://github.com/raphlinus/pulldown-cmark/issues/557) which is fixed by a [PR](https://github.com/raphlinus/pulldown-cmark/pull/558) which has been open since Jan 2022

**Comment by tvanderstad** [comment]
fixed upstream
