### ISSUE TITLE
link problems

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1640]
+ [ ] https://github.com/lockbook/lockbook/issues/1554
+ [ ] https://github.com/lockbook/lockbook/issues/1487
+ [ ] #1570

**Comment by Parth** [comment]
# Link target behavior

+ you should be able to get the cleartext version of any file id
+ the id <--> name relationship should never change
+ if you are finalizing a target file which is linked to (not a link, but a shared file), then you're going to replace it's parent id with the link's parent id
+ when performing operations, say rename, if the id is a shared file (not a link, but something pointed to by a link), you want to operate on the link itself.

**Comment by tvanderstad** [comment]
Smail's issue with finalizing a deleted link to an unshared file should be fixed by this work, because it fails when finalizing a link which currently finalizes some of the target's fields (the target doesn't appear locally once unshared). This should fix that issue because in the target state, finalizing a link doesn't need to finalize the link's target.

Failing test case:
```
#[test]
fn test_clean_sync_deleted_link() {
    let cores = vec![test_core_with_account(), test_core_with_account()];

    let doc = cores[0].create_at_path("welcome.md").unwrap();
    cores[0]
        .share_file(doc.id, &cores[1].get_account().unwrap().username, ShareMode::Write)
        .unwrap();

    cores[0].sync(None).unwrap();
    cores[1].sync(None).unwrap();

    let link_doc = cores[1]
        .create_link_at_path("welcome-path.md", doc.id)
        .unwrap();
    cores[1].sync(None).unwrap();
    cores[1].delete_file(link_doc.id).unwrap();
    cores[1].delete_pending_share(doc.id).unwrap();
    cores[1].sync(None).unwrap();

    another_client(&cores[1]).sync(None).unwrap();
}
```

**Comment by tvanderstad** [comment]
update: just tried this test on your branch and it passes
