### ISSUE TITLE
cli export problems

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#1662]
Any attempt to export a file results in this error: `error: Os { code: 17, kind: AlreadyExists, message: "File exists" }`

**Comment by Parth** [comment]
also acts kinda weird when no path is given:

```
[I] parth@Parths-MBP ~/D/l/l/c/cli (master)> lockbook export todo.md 
exporting 'todo.md'...
[I] parth@Parths-MBP ~/D/l/l/c/cli (master)> ls
Cargo.toml  src/        todo.md/
```

**Comment by steverusso** [comment]
@Parth you don't like assuming current working directory?

**Comment by Parth** [comment]
I do, but if no path is given and I try to export a doc A.md it will:

create `A.md/A.md` instead of just `A.md`.

**Comment by steverusso** [comment]
Ah, I see it now, thanks.
