### ISSUE TITLE
ctrl-arrows & ctrl-shift-arrows operate on the rest of the line instead of by word

### ISSUE THREAD

**Issue by steverusso** [lockbook/lockbook#1695]
`Ctrl-[<|>]` should move the cursor to prev / next beginning of a word, and `Ctrl-Shift` should do the same but with selection. Right now they move to the beginning or end of the line.

(using egui client on linux)

**Comment by tvanderstad** [comment]
I had no idea, sounds like we're going to need an overall review of keyboard shortcuts (if that's what you'd call this) on various platforms
