### ISSUE TITLE
shift enter

### ISSUE THREAD

**Issue by steverusso** [lockbook/lockbook#1701]
Shift enter should insert a new line after the cursor

**Comment by Parth** [comment]
fwiw the default system behavior for me is that shift enter works the same way as just enter on linux, though I think what you're suggesting is better

**Comment by steverusso** [comment]
How are you coming about that? Would like to try myself

**Comment by tvanderstad** [comment]
after the cursor as in, at the end of the cursor's line?

**Comment by steverusso** [comment]
No just after the cursor.
