### ISSUE TITLE
cli: no way to export account without exposing private key

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#1723]
I expect `lockbook account export | pbcopy` to put my private key on my clipboard, but instead it hangs.

`lockbook account export` prints this prompt (and awaits user input)
```
your private key is about to be visible. do you want to proceed? [y/n]:
```

I tried `yes | lockbook account export | pbcopy` but it puts `your private key is about to be visible. do you want to proceed? [y/n]: <private key>` on my clipboard

**Comment by tvanderstad** [comment]
cc @steverusso

**Comment by steverusso** [comment]
Ah yes I made adjustments [in `lbcli`](https://github.com/steverusso/lockbook-x/blob/master/lbcli/account.go#L123-L156) very shortly after that happened to us (essentially checking for if the output is being piped while also adding an option to skip the prompt).

Unsure if we want to adopt that approach as is or tweak it.
