### ISSUE TITLE
numbered list reordering greatness

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1741]

**Comment by tvanderstad** [comment]
Not sure how to reproduce, but I regularly end up with a mess when modifying a numbered list. Need to rework this with a new UX, possibly renumber the whole list from the beginning when there's a relevant change

**Comment by tvanderstad** [comment]
My messes usually came from some weirdness around newlines which was resolved a while ago. The only actionable improvement I'm interested in taking on this for now is for deleting list elements to trigger renumbering.

**Comment by tvanderstad** [comment]
duplicate of https://github.com/lockbook/lockbook/issues/2326
