### ISSUE TITLE
more native iOS text interactions 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1783]
in part:
+ when the selection or text changes in a manner that `UITextInput` is not aware of, we need to report changes to selection & text to the system via [UITextInputDelegate](https://developer.apple.com/documentation/uikit/uitextinputdelegate)
+ UITextInteraction cursors, context menus, selections, and probably #2105 

What's left:

animation quirks:
+ [ ] if cursor is out of bounds it doesn't show partially
+ [ ] the selection is animated differently than the animation inside egui 

gestures:
+ [ ] single tap not working
+ [ ] context menu not showing up
+ [ ] double tap not always working
+ [ ] selection only shown when drag ends (while changing selection)

**Comment by Parth** [comment]
closed in @smailbarkouch todo

**Comment by smailbarkouch** [comment]
closed in https://github.com/lockbook/lockbook/pull/2279
