### ISSUE TITLE
Weird behavior of Tab key in Windows/ Formatting Issues

### ISSUE THREAD

**Issue by MehrotraRahul** [lockbook/lockbook#1964]
Writing a document in windows, faced three issues
1 - Wanted to tab multiple lines together. Selected them and hit tab. They got deleted and I had to type them again. Is there an undo? I couldn't find it. 
2 - When starting a new line, if I hit tab to start at the right place, the line gets deleted. The tab button is behaving like the Delete button when used on an empty line. If I write something, and then go to the beginning and tab, it works on some occasions. 
3 - On other occasions, using the tab button moved the text as expected, but it turned red and changed font

**Comment by Parth** [comment]
1. https://github.com/lockbook/lockbook/issues/1841. Undo is ctrl + z, we can add it to the toolbar for easier feature discovery: https://github.com/lockbook/lockbook/issues/1968
2. tab acting like delete: https://github.com/lockbook/lockbook/issues/1969
3. is actually not a bug, that's a different way to format code, but potentially you wouldn't face that unintuitive behavior if everything else above was not a problem
