### ISSUE TITLE
newlines hidden

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1976]
the text:

```
CAR DETAILS
		Audi A4 2014
	
	
		VIN
	2.0Liter Turbo Quattro
	Trim - Prestige
```

renders as such:

<img width="336" alt="image" src="https://github.com/lockbook/lockbook/assets/821972/4d466867-8bd3-4de9-9637-8ef19a8fb2ee">

as of d4969d1434c82a3733e4575676b4cfca2ec826d7, did not happen in 0.7.5

**Comment by tvanderstad** [comment]
Kind of running into edge cases for the markdown spec here. VSCode's markdown preview renders like this...
<img width="901" alt="Screenshot 2023-08-04 at 10 37 16 AM" src="https://github.com/lockbook/lockbook/assets/6198756/afe249ba-33c8-4255-be80-d55e0f737c8c">
...and StackEdit like this...
<img width="901" alt="Screenshot 2023-08-04 at 10 37 35 AM" src="https://github.com/lockbook/lockbook/assets/6198756/13b85a24-76ad-434b-8052-0bb3ff4d2863">
...and Lockbook, in this yet-unmerged branch, like this...
<img width="247" alt="Screenshot 2023-08-04 at 10 36 40 AM" src="https://github.com/lockbook/lockbook/assets/6198756/1afabc07-3b26-4e46-956d-b8fa0abda09c">
...so given the variety of rendering by different markdown previews already, I'm going to take some liberties and aim for something like what you're requesting

**Comment by tvanderstad** [comment]
related: https://github.com/emilk/egui/issues/3203

**Comment by tvanderstad** [comment]
The linked PR above fixes the issue, but since you've got tab-only lines in your text, you'll be affected by https://github.com/lockbook/lockbook/issues/1983 until egui fixes their issue or I implement a more thorough/complex/begrudging workaround
