### ISSUE TITLE
tab indenting bulleted lists (and other list types) results in unexpected behavior

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2049]
Tab indenting on an empty list item will produce a graphical glitch initially:
<img width="62" alt="Screenshot 2023-09-06 at 12 48 58 PM" src="https://github.com/lockbook/lockbook/assets/20663038/7d18d454-ddc1-4f06-8583-a904f8b7addc">

Then when a character is entered on the glitched list item:
<img width="55" alt="Screenshot 2023-09-06 at 12 49 39 PM" src="https://github.com/lockbook/lockbook/assets/20663038/c88d2e2e-77db-40fe-8eef-aaad89f9c5b8">

**Comment by tvanderstad** [comment]
Are you able to reproduce this on master? I might have fixed it inadvertently with another PR 

https://github.com/lockbook/lockbook/assets/6198756/87e663c9-7f58-4177-bd5f-e3c61a49fa1b

**Comment by tvanderstad** [comment]
Managed to reproduce, this only affects iOS
