### ISSUE TITLE
typing backtick double hyphen transforms to double backtick hyphen in iOS editor

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2050]
`-- becomes ``-

**Comment by tvanderstad** [comment]
actually, it becomes ``—

**Comment by tvanderstad** [comment]
typing `--` on a new line crashes the editor

**Comment by tvanderstad** [comment]
I'm not able to reproduce either of these issues in the simulator on master; can you try deploying master to your phone?

**Comment by tvanderstad** [comment]
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)

**Comment by tvanderstad** [comment]
related: https://github.com/lockbook/lockbook/issues/2090
