### ISSUE TITLE
cannot place cursor in between a line of text on the iOS editor

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2052]

**Comment by tvanderstad** [comment]
Are you able to reproduce this on master? I might have fixed it inadvertently with another PR


https://github.com/lockbook/lockbook/assets/6198756/939d897f-88cc-4567-a4ae-e9c2f40b5321

**Comment by tvanderstad** [comment]
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)

**Comment by tvanderstad** [comment]
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)

**Comment by tvanderstad** [comment]
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)

**Comment by tvanderstad** [comment]
closed by accident

**Comment by Parth** [comment]
probably a yeeting of cursor fixed by travis at some point
