### ISSUE TITLE
command right arrow miscalculated if starting from markdown region

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2061]
1. have more than 1 line, on the first line have a long word with bold in the middle of the line
2. put cursor in middle of word
3. command right
4. find yourself not at the end of the line

**Comment by tvanderstad** [comment]
Well, you're at what _was_ the end of the line before the bold syntax character sequences were captured... This is going to be difficult to fix because egui has to render the next frame before I know where the cursor belongs

**Comment by tvanderstad** [comment]
Maybe this calls for displaying all syntax characters on the current line or in the current paragraph

**Comment by tvanderstad** [comment]
part of https://github.com/lockbook/lockbook/issues/2102
