### ISSUE TITLE
holding down backspace crashes 0.8 iOS

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2080]
reported by @Krishma-Bawa

**Comment by Parth** [comment]
https://github.com/lockbook/lockbook/assets/821972/80274bd4-2996-4d31-9c0a-866f9d9779b1

**Comment by tvanderstad** [comment]
I was able to reproduce on mobile but not on the iOS simulator. Is there a way to view logs on my device? I also have to check if I have the USB-C to lightning cable to deploy to my phone

**Comment by tvanderstad** [comment]
confirmed broken in [0.8](https://github.com/lockbook/lockbook/commit/80cdbd96adacde83b7de6f41a811c63a7bf1aeaa) and fixed on [master](https://github.com/lockbook/lockbook/commit/ef387b2b842ccb9112cf7f8992c9f4db922f5e9b)
