### ISSUE TITLE
cli colored output is busted on windows

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2149]

**Comment by Parth** [comment]
need to investigate further why I made this issue.

[the crate we use](https://github.com/colored-rs/colored) and [this stackoverflow](https://stackoverflow.com/questions/2048509/how-to-echo-with-different-colors-in-the-windows-command-line) seem to suggest that colored output should be fine.

**Comment by tvanderstad** [comment]
![image](https://github.com/lockbook/lockbook/assets/6198756/2a0fd72e-eb31-40b6-a7f2-2f1f4c835dd7)
![image](https://github.com/lockbook/lockbook/assets/6198756/c0596fed-08f6-44e4-a338-3f3e413af372)
seems to be working fine for me

**Comment by Parth** [comment]
Sounds good
