### ISSUE TITLE
Invalid link to Core library on main website

### ISSUE THREAD

**Issue by arncv** [lockbook/lockbook#2167]
Hello,

I came across an issue in the Lockbook website when I was exploring it for the first time. On the main website, there's a link that says **"Use our core library from any programming language"**, but it seems to be broken.

Currently, it's directing me to:
https://github.com/lockbook/lockbook/blob/master/core/src/lib.rs#L91

However, I suspect that the accurate URL should be:
https://github.com/lockbook/lockbook/blob/master/libs/core/src/lib.rs

If you'd like, I'd be more than happy to submit a pull request to resolve this issue.

**Comment by Parth** [comment]
We would absolutely love that. Let me know if you have any problems along the way, happy to help here or on [discord](https://discord.gg/lockbook).
