### ISSUE TITLE
high cpu usage when editor is open (even when idle)

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2192]
To reproduce: open a note in the macos app and observe cpu usage. I wasn't able to reproduce on Windows.

Raised by @Luca409 and also observed by me

**Comment by Parth** [comment]
Before @smailbarkouch's fix:
<img width="762" alt="image" src="https://github.com/lockbook/lockbook/assets/821972/9d1b8b3a-758f-4e31-b554-650dd6b8231a">

After @smailbarkouch's fix:
<img width="758" alt="image" src="https://github.com/lockbook/lockbook/assets/821972/a574eeb1-dd43-4e20-bb16-b659eea56e94">
