### ISSUE TITLE
editor does not detect a bare command keystroke

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2194]
the command key is supposed to un-reveal markdown characters, however the apple integration presently has no way to detect _only_ when a modifier key is pressed.

So in effect on macOS we un-hide the md characters when someone does command+left arrow which is unexpected and weird.

**Comment by tvanderstad** [comment]
I'm pretty sure this is all it takes on windows, apple clients should be similar https://github.com/lockbook/lockbook/pull/2200/files#diff-f726ab1a38ef3aa414710848427d055973cce8d0296697a98f11cf65d4b06b6fR212-R219
