### ISSUE TITLE
bug(iOS): drawing undo/redo not working

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2257]
I was able to use the lasso tool (#2197 fixed for me on iPad v0.8.3) to work around undo not working. They look like they might be in a disabled state?
![IMG_D22B149E5106-1](https://github.com/lockbook/lockbook/assets/4467106/4ece0ac1-d71e-4d32-9675-97d6d8a23e96)

**Comment by smailbarkouch** [comment]
Since we are developing a who new drawing surface (using egui), this iteration of drawing will likely never have working undo/redo. It will certainly be a part of our new iteration.
