### ISSUE TITLE
feat(iOS): inline drawing, resize images/drawings

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2258]
I'd love to be able to embed a drawing in-line similar to how I can with images. The current workaround is creating a drawing, taking a screenshot, cropping the screenshot of the drawing, and then putting the image into the doc. This duplicates the data needed for the drawing, so I'm inclined to delete the drawing after screenshotting it.

Ideally I could crop down the drawing and resize it (and resize images) for small little 1-line drawings embedded in the document.

Bonus would to be able to open an image for annotation

![IMG_39635BDDA97B-1](https://github.com/lockbook/lockbook/assets/4467106/b81a5d5b-209a-4671-be55-62d4ddec8aff)

**Comment by CoreyCole** [comment]
@tvanderstad how do I use this feature?
<img width="818" alt="image" src="https://github.com/lockbook/lockbook/assets/4467106/efea3ee4-133b-4759-8be6-eb4a75344404">

**Comment by tvanderstad** [comment]
Hey @CoreyCole right now you'll have to link via the file id rather than the file path (file paths are coming soon though!). You can get the file id through the menu that comes up when you right click your drawing in the file tree
