### ISSUE TITLE
bug(iOS): weird iPad keyboard behavior

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2259]
Repro iOS v0.8.3:
- tap in the document at the end of the line
- hit enter on the keyboard (intending to create a new line)
- the cursor shows blinking in multiple places (either doc+title or doc+search in sidebar)
- I'm unable to create a new line with the iPad keyboard

Not sure what is going on, but I took a screen recording. It is hard to tell in the video, but I am hitting enter on the iPad keyboard. In the video it shows the cursor getting duplicated into the doc title, but I also observed the same issues of keyboard enter putting the cursor in the sidebar search bar.

If I pulled up the onscreen keyboard, I was able to work around it (enter worked to create a new line)

After minimizing the application to share the screen recording, the problem went away--keyboard worked fine again.

https://github.com/lockbook/lockbook/assets/4467106/f51ba5ff-057f-435a-9283-adf1905df67f

**Comment by smailbarkouch** [comment]
Fixed by #2279
