### ISSUE TITLE
bug(iOS): weird bullet list behavior

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2260]
On this list when I create a new line and press tab on iPad keyboard, it looks like it turns into heading size until I start typing characters into the indented list line

https://github.com/lockbook/lockbook/assets/4467106/2f78d689-b305-442c-b698-7e3517489766

**Comment by CoreyCole** [comment]
https://github.com/lockbook/lockbook/assets/4467106/b01b2483-4c64-4ed2-bb5f-44b3e6af4d4f

another case where indenting a sub list bullet item also indented a top level bullet item

**Comment by tvanderstad** [comment]
First one's a markdown quirk - putting a hyphen under a line turns it into a header. Second one's covered by https://github.com/lockbook/lockbook/issues/2372
