### ISSUE TITLE
workspace tab strip does not scroll

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2323]
When there's too many tabs open, can't navigate or see all of them (either a sliding motion without diminishing the tab size or minimize all the tab sizes once the space is filled up would be nice to browse through all tabs)

**Comment by ad-tra** [comment]
requested by @mahakanakala

**Comment by ad-tra** [comment]
solved by https://github.com/lockbook/lockbook/pull/2280/commits/2a05c1bb0c4fdd8b0efd812c3555e70360fb820b
