### ISSUE TITLE
selection & eraser icons render as □

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2330]
<img width="1012" alt="Screenshot 2024-01-15 at 11 01 53 AM" src="https://github.com/lockbook/lockbook/assets/6198756/c440fdd2-889c-4731-8092-a5c907219e2f">

**Comment by ad-tra** [comment]
fixed by https://github.com/lockbook/lockbook/pull/2280/commits/2e8ed0ab9b55d683d04e2e9912046d64bb391701
