### ISSUE TITLE
update egui

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2380]
at-least for #2379

**Comment by tvanderstad** [comment]
this will also likely fix https://github.com/lockbook/lockbook/issues/1983, which itself fixes https://github.com/lockbook/lockbook/issues/2283

**Comment by tvanderstad** [comment]
note: will depend on https://github.com/hasenbanck/egui_wgpu_backend/pull/80

**Comment by Parth** [comment]
merged in #2582
