### ISSUE TITLE
markdown todo touch issues mobile

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2460]
impossible to toggle

requested by @krishma-bawa

**Comment by tvanderstad** [comment]
I investigated and the size of the button seems not to be an issue. I made the buttons absurdly large and I'm seeing a bunch of weird behavior including:
* clicking a checkbox may or may not toggle it, and if it does, it may update after a <1s delay
* double-clicking a checkbox reliably instantly toggles it but also selects a nearby word

You can try running on branch `bigger-checkbox-hitbox`.
Here's a demo:

https://github.com/lockbook/lockbook/assets/6198756/50077c5c-8632-4fd0-a3d2-598f80b60b97
