### ISSUE TITLE
ios: crash "Fatal error: Unexpectedly found nil while unwrapping an Optional value"

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2521]
on master and on smail/fix-image-paste when i click on any tab (repro'd on welcome.md) I have 1 file open and click the welcome.md tab and it crashes with
> Fatal error: Unexpectedly found nil while unwrapping an Optional value

![image](https://github.com/lockbook/lockbook/assets/4467106/de1e48ac-950c-4abf-9d2b-4f9a4721f3b4)

**Comment by tvanderstad** [comment]
@smailbarkouch do we have any reason to believe this is still an issue?

**Comment by smailbarkouch** [comment]
This particular unwrap doesn't happen, but the underlying issue may still exist. That underlying issue is workspace not telling the platform to refresh its files cache when something is imported.
