### ISSUE TITLE
Focus on file scroll bar instead of document

### ISSUE THREAD

**Issue by Kjets22** [lockbook/lockbook#2572]
If you open enough files where you get a file scroll bar the error occurs. It is expected that I should still be able to edit the document, however, what happens is that the focus becomes the scroll wheel for the files at the top and it becomes a struggle to edit or do anything in the document.

**Comment by Parth** [comment]
@Kjets22 can you add a video that someone could use to replicate the issue?

**Comment by kjetthe** [comment]
[video for how to replicate issue](https://discord.com/channels/1014184997751619664/1214974695850639360/1214979468649832458)

**Comment by Kjets22** [comment]
[video for how to replicate issue](https://discord.com/channels/1014184997751619664/1214974695850639360/1214979468649832458)
