### ISSUE TITLE
Inaccurate terminology for creating a new folder

### ISSUE THREAD

**Issue by mahakanakala** [lockbook/lockbook#2573]
When attempting to create a new folder within the interface, the prompt or field where the user enters the name is labeled as "filename." This is inaccurate as users are creating **folders** not files, not individual files themselves. Ideally, it should say "folder name."

![image](https://github.com/lockbook/lockbook/assets/96635744/25a3c6ea-6dc6-4392-ac23-3cb15bda0bc8)

**Comment by tvanderstad** [comment]
fixed by https://github.com/lockbook/lockbook/pull/2826
