### ISSUE TITLE
cannot edit document when more tabs than window width

### ISSUE THREAD

**Issue by CoreyCole** [lockbook/lockbook#2587]
On macos, cannot edit the document with too many open tabs. I can only edit after I close enough tabs (no more horizontal scrollbar)

https://github.com/lockbook/lockbook/assets/4467106/d3fe85bc-b339-420b-9bc1-12e3f7d28d9a

**Comment by ad-tra** [comment]
hey corey, thanks for reporting the issue, it's already tracked it on #2572

this is pretty high severity so there's an open fix pr that will be merged soon

**Comment by CoreyCole** [comment]
whoops my bad I tried searching for an open issue about it but I was using the wrong keywords
