### ISSUE TITLE
0.9.1 QA

### ISSUE THREAD

**Issue by ad-tra** [lockbook/lockbook#2615]
# egui 
- [x] file picker has mismatched colors. 
- [x] file tree missing colors of folders 
- [x] ctrl + , command to pull up settings doesn't work
- [x] tolerance for dirty lockbook is too low. increase it from 1 to 5 or so 
- [x] pdf sidebar, thumbnails are too dark
- [x] pdf snap scroll is broken 
- [ ] scrolling vertical bar on the editor triggers text selection 
- [ ] workspace returns "sync successful message" even though it failed (usage capped)
- [ ] it's too easy to trigger a file drag an drop on the file tree
   -  add some time throttle 
   -  false positive trigger on: 
      -  scrolling the horizontal or vertical bar triggers 
      - ui is disabled by modal
      - the context menu is visible
- [ ] unnecessary horizontal scroll on file tree
- [ ] canvas: long paths can't be parsed
- [ ] new folder button on welcome screen is broken 
   - [ ] logo is too faint 
- [ ] logo on sign up / sign in too faint and too large 
- [ ] no error toast on unexpected rename from file tree and tab 
- [ ] toast in light mode has invisible background 
- [ ] missing padding on create new folder modal 
- [ ] search bar on file tree doesn't have padding
- [ ] too many flashes on the search bar feature 
- [ ] sometimes the search spinner is stuck loading even thought the search is done
- [ ] ctrl + space search could use some more padding. 
- [ ] can't delete a selected file in the file tree by pressing delete or backspace 

---

# Linux 
- [ ] dropping an image into the client (not the editor or canvas) causes the app to crash with err message of `thread 'main' panicked at clients/linux/src/main.rs:13:20: called `Result::unwrap()` on an `Err` value: "dropped file has non-file protocol`
# Windows

# macOS

# iOS

# android

**Comment by Parth** [comment]
https://github.com/lockbook/lockbook/assets/821972/90895d27-58cd-42da-8642-9612fb265a5e
