### ISSUE TITLE
Tab bar moves with text selection

### ISSUE THREAD

**Issue by mahakanakala** [lockbook/lockbook#2627]
When selecting text within documents, the tab bar at the top of the screen also moves along with the selection. 

https://github.com/lockbook/lockbook/assets/96635744/b9739c77-456a-411c-a2db-a7588f0b011f

https://github.com/lockbook/lockbook/assets/96635744/8ecc8299-1dc4-47aa-a3a5-1775ca5853f9

**Comment by ad-tra** [comment]
hey @mahakanakala thanks for reporting the issue, this has been fixed on master thanks to the egui version update. the fix will be released on the app stores this week. stay tuned!
