### ISSUE TITLE
`no_folder_selected` crashes macOS in the background sometimes

### ISSUE THREAD

**Issue by smailbarkouch** [lockbook/lockbook#2635]
`no_folder_selected(wsHandle)` is the crashing statement in the `draw` function of `macMTK`

**Comment by tvanderstad** [comment]
possibly a dupe of https://github.com/lockbook/lockbook/issues/2580

**Comment by smailbarkouch** [comment]
Likely fixed by https://github.com/lockbook/lockbook/pull/2678. Has not been reproduced since then.
