### ISSUE TITLE
conflicts happen more often than expected

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2716]
Unsure how to reproduce, but I often find edit conflicts in documents I didn't concurrently edit eg everytime I open a document it has merge conflicts no matter how many times I resolve them.

Possibly related: #558

**Comment by Parth** [comment]
Agreed also have experienced this

**Comment by tvanderstad** [comment]
My best guess right now is that this happens because the merge conflict markers are synced and then I concurrently resolve the conflict on each device but in slightly different ways

**Comment by tvanderstad** [comment]
Closing as non-reproducible
