### ISSUE TITLE
capture character excellence

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2724]
+ command should un-capture the line the cursor is on
+ paragraph shouldn't un-capture all by default

https://github.com/lockbook/lockbook/assets/821972/721de5ef-cc4c-4c53-ae42-dc9feec9f36b

**Comment by tvanderstad** [comment]
When dragging to select, if selection triggers un-capture, the bottom point of the selection can change (it's by screen position instead of cursor position). Perhaps selection shouldn't un-capture until the drag is released.
