### ISSUE TITLE
tab strip & editor focus conflict 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2725]
+ have 2 tabs open
+ be on second tab
+ command + 1
+ arrive at first tab
+ click on second tab
+ see `1` inserted into your document

**Comment by Parth** [comment]
I'm not able to reproduce this anymore, something else strange was happening at this time: I was not able to scroll the editor until I hit escape.

**Comment by tvanderstad** [comment]
I have also had problems scrolling until I clicked in the editor

**Comment by Parth** [comment]
Possibly related: https://github.com/lockbook/lockbook/issues/2726
