### ISSUE TITLE
sometimes editor loses focus 

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2726]
Still searching for reliable ways to reproduce, but occasionally while using macOS the editor will seemingly stop being interactive despite clicking on the editor. Interactivity will be restored when you tap escape, which makes me think this is a focus issue.

**Comment by Parth** [comment]
command tab seems to play a role in this

**Comment by Parth** [comment]
you can hit any key, not just escape, to regain focus

**Comment by tvanderstad** [comment]
also observed on iPad: https://discord.com/channels/1014184997751619664/1288694029889830973/1288700745901674609
