### ISSUE TITLE
Maximum filename length is too short

### ISSUE THREAD

**Issue by BuriedInTheGround** [lockbook/lockbook#2937]
## Problem

Personally, I find the current maximum filename length ([64 characters](https://github.com/lockbook/lockbook/blob/ca14d52cf0e242dd2baf01a26f5de6ae90487164/libs/lb/lb-rs/src/shared/filename.rs#L3)) too short. I've already encountered this problem three separate times when creating new notes. (If you're interested in why the long names, in all those cases it's because of university courses names, which I like to keep in their full form.)

## Proposal

From a quick online search, it seems that 255 bytes is the general rule for maximum filename length (let's consider the *nix world, since Windows is peculiar about path lengths). Therefore, I propose extending the maximum filename length in Lockbook to 230 characters (which [would add up to 254 for the encrypted name](https://github.com/lockbook/lockbook/blob/ca14d52cf0e242dd2baf01a26f5de6ae90487164/libs/lb/lb-rs/src/shared/filename.rs#L4), 1 byte shorter than consensus for a nice and round maximum length and tiny future proofing).

**Comment by Parth** [comment]
Okay I'll expand the limit, I'm open to 230, but for reference what is the minimum increased filename size you would consider acceptable?

**Comment by BuriedInTheGround** [comment]
My longest title is 75 characters, right now. I think I'd accept a doubling of the current limit at minimum, so 128.

**Comment by Parth** [comment]
Okay thank you for the constraints

**Comment by Parth** [comment]
Although this issue will close when #2939 is merged, you won't be able to do this until our server is deployed. We do this when we release the clients, so just watch out for a new release.
