### ISSUE TITLE
Characters duplication in Android editor

### ISSUE THREAD

**Issue by BuriedInTheGround** [lockbook/lockbook#2938]
The following behavior (see video) occurs on my Android 14 device with Lockbook 0.9.10, making the app unusable for writing.

https://github.com/user-attachments/assets/6ae7d9a0-7a5e-41c1-9233-37fdb95aaa92

**Comment by BuriedInTheGround** [comment]
Update: I performed some tests and found the following.
- This behavior only happens with letters, both uppercase and lowercase.
- Numbers and symbols work fine, both on insertion and deletion.
- The problem disappears when writing letters between other letters, `aaaaLIKE THISaaaa`.

**Comment by Parth** [comment]
@BuriedInTheGround which keyboard do you use? We weren't able to immediately reproduce with Samsung or googles keyboard.

**Comment by BuriedInTheGround** [comment]
I use the default AOSP keyboard, package name `com.android.inputmethod.latin` version 14, repackaged by the GrapheneOS team (see [the corresponding repo](https://github.com/GrapheneOS/platform_packages_inputmethods_LatinIME)).

**Comment by Parth** [comment]
Thank you, we'll investigate further

**Comment by BuriedInTheGround** [comment]
> The problem disappears when writing letters between other letters, aaaaLIKE THISaaaa.

Update: A single letter after is enough to make the problem disappear. See video.

https://github.com/user-attachments/assets/5aad664d-e8be-478c-a66e-e67e2c5c4a64

**Comment by smailbarkouch** [comment]
Hey @BuriedInTheGround, I lead the Android development. I'm some difficulty reproducing the issue on other AOSP based keyboards (those being the GBoard and [Simple Keyboard](https://play.google.com/store/apps/details?id=rkr.simplekeyboard.inputmethod)).

Do you have any special configurations on your keyboard (specific settings turned off/on)? In addition, can you provide me with an APK of your keyboard?

**Comment by tvanderstad** [comment]
I suspect this has something to do with marked text 🤔

**Comment by BuriedInTheGround** [comment]
Hey @smailbarkouch, first, thanks for working on it. I have never changed the default configuration of my keyboard. However, your question got me into actually trying to change some settings and test various combinations. I found out that disabling the option "Show correction suggestions" (which corresponds to the `prefs_show_suggestions` key in the `strings.xml` file in the app source code) makes the problem disappear completely! Unfortunately, I'd like to keep that option turned on, so this is still a problem for me.

I'm unable to provide you with the APK, but if you can compile from source, you should get precisely the same app as the one I have. The repo is [the one from the GrapheneOS team](https://github.com/GrapheneOS/platform_packages_inputmethods_LatinIME), as I use GrapheneOS. Currently, the settings report version 14 and versionCode 30 for me.

If you're going to look into the app source code, I found that the `prefs_show_suggestions` setting controls the boolean output of the `isSuggestionsEnabledPerUserSettings()` function and only that. Hope this helps.

**Comment by smailbarkouch** [comment]
Hey @BuriedInTheGround, happy to hear disabling that makes the problem disappear. Of course we want that setting to work, so I'll make strides to figure out what's going on. That starts with getting the APK, so I'll try to build it from source. I'll keep you posted as I resolve this issue.

**Comment by BuriedInTheGround** [comment]
Hey @smailbarkouch, here's the (zipped) APK. I hope it'll work on your testing device!

[platform_packages_inputmethods_LatinIME.zip](https://github.com/user-attachments/files/17603541/platform_packages_inputmethods_LatinIME.zip)

**Comment by smailbarkouch** [comment]
Hi @BuriedInTheGround, unfortunately I'm still having difficulty reproducing the issue. I was able to install your provided APK, but I don't see a setting called "Show correction suggestions." This is what I see:

<img src="https://github.com/user-attachments/assets/af37bbd6-a7c4-47a2-92a0-ca0d6acba657" height="500" />


In addition, I set my language to Italian (it looks like you use that in your video), and I updated my device to Android 14. Unfortunately, neither worked. I will retry reproducing this issue on my Samsung device, but let me know if anything comes to mind regarding the difference in settings.

**Comment by BuriedInTheGround** [comment]
Hi @smailbarkouch, thanks for the update. Indeed, I'm using Italian (since it's my native language). Also, I'm on Android 15 right now, but nothing have changed about this issue from Android 14.

I don't really how to explain the differences. This is how I access the said setting.

https://github.com/user-attachments/assets/6c616a4d-8d52-44f1-bfba-1eaa3065a1cd

**Comment by Parth** [comment]
So @smailbarkouch and I did a round of testing in a call, we discovered that we were never actually able to get the apk you provided us to run. It crashes immediately for input in any app. We searched for apks from AOSP and they behaved similarly. Finally we just sampled some popular keyboards, and were able to reproduce the problem using [Futo](https://github.com/futo-org/android-keyboard) (also a fork of AOSP Latin IME). The experience seems very similar to what you're showing and @smailbarkouch has some leads but will likely need some more time to investigate to finally pin this issue down. https://github.com/user-attachments/assets/8153eefc-7643-459e-af08-12626099c0dd

We'll keep you posted

**Comment by BuriedInTheGround** [comment]
Thanks @Parth! The issue from your video seems exactly the same as mine, so I'm confident you're on the right track. I'll wait for updates, and let me know if there's anything I can do to help! :)

**Comment by Parth** [comment]
Nice job @smailbarkouch, @BuriedInTheGround this should get released shortly

**Comment by BuriedInTheGround** [comment]
Awesome, thank you!
