### ISSUE TITLE
context menu doesn't open on Android

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2942]

**Comment by tvanderstad** [comment]
@smailbarkouch can you remind me the contract here?

On Apple Notes, double-tapping to select text opens a context menu, then tapping it again closes it. Should the editor indicate a context  menu in its response every frame, or just on the frame its open? In other words, is editor responsible for signaling when to close the menu?

**Comment by smailbarkouch** [comment]
@tvanderstad  The editor should only indicate the frame in which the context menu was opened. I will open it that frame and keep it open, and I'll determine when it should be closed.
