### ISSUE TITLE
markdown code block refinements

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2958]
- add a background
- don't change font color
- highlight language keywords (best effort) tracked by https://github.com/lockbook/lockbook/issues/2969
- copy button tracked by https://github.com/lockbook/lockbook/issues/2450

**Comment by BuriedInTheGround** [comment]
> copy button

Is it possible to have this only when hovering the block? I suggest this to minimize the visual clutter, at least on devices with a pointer.

**Comment by tvanderstad** [comment]
@BuriedInTheGround Yeah, certainly! We have a working example of that with the tab strip, where the close button for a tab only appears when hovering the tab, so should be no problem to get it working like that here as well

**Comment by tvanderstad** [comment]
Speaking of visual clutter, would be great to get your feedback on some visual updates I put together yesterday:
* https://github.com/lockbook/lockbook/pull/2959 replaces the floating toolbar on desktop with the smaller one we're already using on mobile and adds features like making the 'B' for bold blue when your cursor's in bold text
* https://github.com/lockbook/lockbook/pull/2960 makes our tab strip more minimal and less cluttered
* https://github.com/lockbook/lockbook/pull/2961 gives code blocks a background so they're visually distinguished without needing to be a different font color

**Comment by smailbarkouch** [comment]
@tvanderstad It's important to mention that hovers aren't communicated to the markdown editor on iPad due to some conflicts with Apple's own native cursor logic. So on that platform, you probably just want to keep it visible.

**Comment by tvanderstad** [comment]
@smailbarkouch got it 👍 I don't have a pointer for my iPad so I treat it like a touch-only device by default
