### ISSUE TITLE
canvas background fill

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#3003]
use egui's extreme bg color to match the color of the active tab in the tab strip

**Comment by ad-tra** [comment]
This only happens on the egui right?

**Comment by tvanderstad** [comment]
Happens on apple clients too - I think I removed a thing that added a global background to FFI clients to make it consistent with egui. I can prob find a decent place in canvas to draw a rectangle if you don't want to bother

**Comment by ad-tra** [comment]
I can do it this week, might be a bit tricky to figure out the layer order of that rect such that it doesn't interfere with the canvas render, the toolbar and any other UI overlay

**Comment by tvanderstad** [comment]
https://github.com/lockbook/lockbook/pull/3004 does the job with the background but now the toolbars are the same color
