### ISSUE TITLE
undo gesture fires erroneously

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#3042]
- adam says the gestures handler should just cancel gestures
- but what is acceptable to Parth is don't do PressAndHold and only fire this gesture on release to simplify things. Obviously a pen input in between palm would cancel the gesture

Requested by @Parth 
Requested by @MehrotraRahul

**Comment by tvanderstad** [comment]
I have also experienced undo firing erroneously

**Comment by ad-tra** [comment]
this is in my top priorities along with canvas collaboration. so it'll be fixed shortly. 
thanks for your patience :D

**Comment by ad-tra** [comment]
fixed by #3090
