### ISSUE TITLE
floating cursor

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#3049]
after failing to do #3048 I try to use floating cursor which is also kinda a bad time: 

I'm able to scroll down using floating cursor, but I'm not able to scroll up.

I think we're probably also overdue for a bit of an inquiry into floating cursor "excellence". We should compare our implementation to other apps and ensure that the solution is flexible and fluid. I can help constrain this inquiry as a heavy user of floating cursor.

https://github.com/user-attachments/assets/78eaed71-d4fd-4a97-bb42-395cecf71aa0

**Comment by smailbarkouch** [comment]
fixed by #3190

**Comment by smailbarkouch** [comment]
It will auto scroll near the edges now, although I don't know how my implementation differs from Apple Notes. I can launch some inquiry into this in the future.
