### ISSUE TITLE
dismiss pen toolbar

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#3079]
Using canvas on iPad, after adjusting the color of my stroke, I can't dismiss the pen toolbar/menu except by doing the following:
* drawing
* changing the tool
* toggling zen mode

It would be nice if the toolbar had an 'x' or closed itself when you tap the pen icon in the persistent toolbar (as if changing the tool to the pen even though the pen is already the active tool).

**Comment by ad-tra** [comment]
yeah i share your desire. i think hiding the popover by clicking on the pen makes the most sense. i'll do that.
