### ISSUE TITLE
Color unification

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#317]
Look at the screenshots below. Want to unify our colors to this, don't worry about other styling for now

@raayan please drop some iPhone screenshots here for @SmailBarkouch

**Comment by raayan** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-22 at 00 51 43](https://user-images.githubusercontent.com/2370497/95031780-d80bc880-0685-11eb-99dc-f548a81fd807.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 07 45](https://user-images.githubusercontent.com/2370497/95031781-d80bc880-0685-11eb-85e0-a47550a84b34.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 07 47](https://user-images.githubusercontent.com/2370497/95031782-d80bc880-0685-11eb-9215-77bdab122d75.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 07 50](https://user-images.githubusercontent.com/2370497/95031783-d8a45f00-0685-11eb-8bdb-fe783a83892c.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 09](https://user-images.githubusercontent.com/2370497/95031784-d8a45f00-0685-11eb-991a-d231acf24cf4.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 15](https://user-images.githubusercontent.com/2370497/95031786-d8a45f00-0685-11eb-997b-3b0108c46095.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 20](https://user-images.githubusercontent.com/2370497/95031787-d8a45f00-0685-11eb-8a08-7c40b28d411b.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 22](https://user-images.githubusercontent.com/2370497/95031788-d93cf580-0685-11eb-831b-e4332f183ce2.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 27](https://user-images.githubusercontent.com/2370497/95031789-d93cf580-0685-11eb-986c-e0a06c74a7c5.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 31](https://user-images.githubusercontent.com/2370497/95031790-d93cf580-0685-11eb-8ef5-80487aeff8d4.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-04 at 21 08 38](https://user-images.githubusercontent.com/2370497/95031791-d93cf580-0685-11eb-94ce-c72f906f0ee9.png)

**Comment by raayan** [comment]
@SmailBarkouch pics are in!

**Comment by raayan** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 04](https://user-images.githubusercontent.com/2370497/95630629-2e935100-0a50-11eb-9b89-ae3e2903fac8.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 07](https://user-images.githubusercontent.com/2370497/95630631-2f2be780-0a50-11eb-8c6a-197541fc6670.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 10](https://user-images.githubusercontent.com/2370497/95630632-2f2be780-0a50-11eb-9843-f5ed2c5389c7.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 13](https://user-images.githubusercontent.com/2370497/95630633-2f2be780-0a50-11eb-8fcd-9948a3636f06.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 16](https://user-images.githubusercontent.com/2370497/95630634-2f2be780-0a50-11eb-9f88-ae49b984919a.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 17](https://user-images.githubusercontent.com/2370497/95630636-2f2be780-0a50-11eb-9fa1-0f7b9ee4c788.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 20](https://user-images.githubusercontent.com/2370497/95630638-2fc47e00-0a50-11eb-8669-2e66ef1471ef.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 24](https://user-images.githubusercontent.com/2370497/95630639-2fc47e00-0a50-11eb-9e5a-bbe57b9dabb4.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 26](https://user-images.githubusercontent.com/2370497/95630640-2fc47e00-0a50-11eb-858b-6018518e2fb0.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 28](https://user-images.githubusercontent.com/2370497/95630642-2fc47e00-0a50-11eb-93d4-a16a48d22d9a.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 31](https://user-images.githubusercontent.com/2370497/95630643-2fc47e00-0a50-11eb-9410-636b60de227d.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-09 at 16 54 38](https://user-images.githubusercontent.com/2370497/95630644-305d1480-0a50-11eb-987a-5c69cf3f2f6a.png)


@SmailBarkouch dark pics
