### ISSUE TITLE
Get Lockbook categorized under creativity

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#405]
For the purposes of screen time Lockbook should be placed in creativity. 

![image](https://user-images.githubusercontent.com/821972/99153319-cac6fe00-2675-11eb-8f6e-3890e27c2415.png)

**Comment by raayan** [comment]
Disagree

**Comment by raayan** [comment]
Already done for "Productivity" likely not showing up because this is in TestFlight right now
