### ISSUE TITLE
Improve UI/UX around creating "New" file

### ISSUE THREAD

**Issue by steverusso** [lockbook/lockbook#419]
Currently, there's a solitary "New" dialog that uses `create_at_path` which will create a directory if there is a trailing slash and a document otherwise.
* Instead, let's separate this into two explicit avenues: creating a document and creating a folder. This way, a user knows for sure which is being created and doesn't have to worry about forgetting a slash or something. Additionally, these New dialogs should take a parameter that is the location where the new thing is intended to be created. This way, the input field can be prefixed with the directory under which the user is creating a new file. This is purely for UX and will be leveraged once... :arrow_down: 
* Add 'New Document' and 'New Folder' items to the file tree's popup menu. Send the selected files ID with the Msg so that the input fields can be prefixed with its path. These items should only be enabled if there is exactly one file selected.

**Comment by Parth** [comment]
Duplicate: #733
