### ISSUE TITLE
Use gradle image for kotlin interface tests and android dockerfile

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#485]
Use [this](https://hub.docker.com/_/gradle) for the `Dockerfile.kotlin_interface_tests` dockerfile

**Comment by SmailBarkouch** [comment]
The gradle starting image isn't really necessary since the gradle wrapper used to build android in the `Dockerfile.android` and `Dockerfile.kotlin_interface_tests` automatically downloads itself. This is through the specified version in the `gradle-wrapper.properties` file.

**Comment by Parth** [comment]
motivation would be to *not* use the wrapper, and use the `gradle` binary in the image, perhaps the whole image will be smaller, and less error prone, I'll close this for now, if we ever see kotlin tests stall for 6 hours again, I'll reopen this and we'll try it.

**Comment by SmailBarkouch** [comment]
The issue is being reopened since a starting gradle image can save time. Everytime we do `./gradlew assemble` it downloads the specified gradle image on demand and it isn't cached, and with a gradle image it will be cached always.
