### ISSUE TITLE
lockbook status doesn't correctly show the last time you synced 

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#506]
To reproduce:
1. Create a new lockbook account on CLI
2. Create a file with any name
3. Sync your lockbook
4. Run lockbook status  and it should show that you just synced
5. Then create another new file
6. Sync lockbook
7. Check your status once more and it will show the time since the first sync, not the last

**Comment by Parth** [comment]
I believe https://github.com/lockbook/lockbook/pull/574 solves this, please re-open and slack me if I'm wrong
