### ISSUE TITLE
Client to Core content merge resolution

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#558]
+ [ ] in `edit_content` take a `content_version` along with the new contents of a file, and reject edits to files who's `content_version` have been incremented as a result of a sync
+ [ ] provide a way to merge the contents of a file when core rejects an edit

**Comment by Parth** [comment]
almost certainly going to be related to https://github.com/lockbook/lockbook/issues/558

**Comment by tvanderstad** [comment]
> almost certainly going to be related to #558

that's this issue - did you mean another one?
