### ISSUE TITLE
Set active style to markdown style on MacOS

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#754]
steps to reproduce:
1. make a markdown doc in the macos app
2. type `# Anything`
3. wait for markdown render
4. keep typing on the same line

expected behavior:
newly typed text same style as rest of line instantly

actual behavior:
newly typed text is always the same style and you have to wait for markdown render to fix it

**Comment by Parth** [comment]
We can use a lot of heuristics about what the style of the current line should be:
+ If the first character of a line is `#` then you should make until the rest of the line a heading
+ If they press enter you should assume plain text

+ if the current line is a bullet, then use the same style and insert a bullet
+ if they open a code fence, open another code fence
