### ISSUE TITLE
tracking: gtk sourceview spellcheck

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#887]
Newest gedit app, on latest everything has spell check broken too, probably we need a tracker for some consumer facing bug

**Comment by SmailBarkouch** [comment]
Gspell seems to be [staying only in gtk-3](https://gitlab.gnome.org/GNOME/gspell/-/issues/17) and [new spellcheck support is being added](https://gitlab.gnome.org/GNOME/gtk/-/issues/3814) (whether or not that does include gspell anymore). We should watch the progression of that issue.
