### ISSUE TITLE
tracking: gtk4 treeview drag and drop

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#951]
our problem? ubuntu problem?

**Comment by Parth** [comment]
@tvanderstad can you tell me if this is broken on pop!_os?

**Comment by tvanderstad** [comment]
it is broken on Pop!_OS

**Comment by Parth** [comment]
I wonder if #903 would just solve this problem

**Comment by Parth** [comment]
@steverusso add tracker

**Comment by steverusso** [comment]
* https://gitlab.gnome.org/GNOME/gtk/-/issues/1603
* https://gitlab.gnome.org/GNOME/gtk/-/issues/4669
