### ISSUE TITLE
make metrics great again

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#988]
There was an error thrown by [pager duty](https://lockbook.pagerduty.com/incidents/Q152IEQ35P8FCW), originating from server's metrics service. 

```
Cannot retrieve file usage for id: a554286c-6776-4be4-bd1c-6977d4bcb926
```

**Comment by Parth** [comment]
```
parth@ip-172-31-89-187:~$ redis-cli 
127.0.0.1:6379> keys *a554286c-6776-4be4-bd1c-6977d4bcb926*
1) "id-version:a554286c-6776-4be4-bd1c-6977d4bcb926-1645244786883:encrypted_document"
2) "file_id:a554286c-6776-4be4-bd1c-6977d4bcb926:metadata"
3) "file_id:a554286c-6776-4be4-bd1c-6977d4bcb926:size"
127.0.0.1:6379> get file_id:a554286c-6776-4be4-bd1c-6977d4bcb926:size
"{\"file_id\":\"a554286c-6776-4be4-bd1c-6977d4bcb926\",\"size_bytes\":128036}"
127.0.0.1:6379> 
```
?

**Comment by SmailBarkouch** [comment]
Hmm, that is very confusing, maybe metrics tried to get the size of that file before the key value pair was generated. If this is the case, it may make sense then to allow documents with no file usage to not fail in metrics.

**Comment by Parth** [comment]
practically speaking we never create a file and don't write contents to it. But while a file is new, it has 0 size. Can you write a test that verifies that new files will have no size (not 0 size).

https://github.com/lockbook/lockbook/blob/master/core/tests/get_usage_tests.rs

all of these immediately write the file as soon as it's created.

You know a file is new if its content version is `0`. So you can add that check right here: https://github.com/lockbook/lockbook/blob/master/server/server/src/metrics.rs#L162.

**Comment by Parth** [comment]
We should also have logs for when the metrics loop starts, so that we can, at a glance tell if metrics are running.

**Comment by Parth** [comment]
And we should fix this error: https://github.com/lockbook/lockbook/blob/master/server/server/src/metrics.rs#L51

we should catch all errors and then the page should be: `"interrupting metrics loop due to error: {}"`.

**Comment by Parth** [comment]
And we should fix our computation of documents: https://github.com/lockbook/lockbook/blob/master/server/server/src/metrics.rs#L87

currently includes deleted documents.

**Comment by Parth** [comment]
And we should fix whatever is going on here: 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/821972/154827481-2212db73-146f-40b5-b0dd-78e934e85697.png">

**Comment by Parth** [comment]
It would be nice if usage was split up by user
